name: Update GitHub pages
on:
  schedule:
    - cron: '47 11 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub API Request
        uses: octokit/request-action@v2.1.0
        with:
          route: POST /repos/${{github.repository}}/pages/builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
